package com.hoz.hozitech.domain.enums;

public enum BusinessErrorCode {
    EMPTY_CHECKOUT_ITEMS,
    USER_NOT_FOUND,
    ADDRESS_NOT_FOUND,
    ADDRESS_NOT_OWNED,
    CART_ITEM_NOT_FOUND,
    CART_ITEM_UNAUTHORIZED,
    VARIANT_NOT_FOUND,
    PRODUCT_NOT_AVAILABLE,
    VARIANT_NOT_AVAILABLE,
    INSUFFICIENT_STOCK,
    PRICE_CHANGED,
    INVALID_PRODUCT_COUPON,
    INVALID_SHIPPING_COUPON,
    COUPON_NOT_ACTIVE,
    COUPON_NOT_STARTED,
    COUPON_EXPIRED,
    COUPON_USAGE_LIMIT_EXCEEDED,
    COUPON_MIN_ORDER_NOT_MET,
    IDEMPOTENCY_KEY_REQUIRED,
    INVALID_PAYMENT_METHOD,
    PAYMENT_METHOD_UNAVAILABLE,
    WEBHOOK_IDEMPOTENCY_KEY_REQUIRED,
    WEBHOOK_ORDER_NOT_FOUND,
    INVALID_PAYMENT_STATUS
}
